name: workflow for main branch

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-the-containers:
        runs-on: ubuntu:latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                docker compose up -d --build