name: workflow for main branch

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-the-containers:
        runs-on: ubuntu:latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                docker ps -a
                docker compose up -d --build
    allow-production:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - run: echo "Code being added to main"