name: workflow for main branch

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-the-containers:
        runs-on: ubuntu:latest
        steps:
            - run: echo "Hello"